services:
  flashcards-backend:
    build: ./backend
    container_name: flashcards-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      my-postgres-db:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      apm-server:
        condition: service_started
      minio-container:
        condition: service_started
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ACCESS_TOKEN_SECRET_KEY=${ACCESS_TOKEN_SECRET_KEY}
      - REFRESH_TOKEN_SECRET_KEY=${REFRESH_TOKEN_SECRET_KEY}
      - PEPPER=${PEPPER}
      - CSRF_SECRET_KEY=${CSRF_SECRET_KEY}
      - MINIO_ENPOINT=${MINIO_ENPOINT}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}

  my-postgres-db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [
          "CMD",
          "curl",
          "-s", # silent
          "-f", # fail fast (non-200 exits with error)
          "-u",
          "elastic:${ELASTICSEARCH_PASSWORD}",
          "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  minio-container:
    image: minio/minio
    container_name: minio-container
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.10.2
    container_name: apm-server
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
    command: >
      apm-server -e -d "*"
        -E apm-server.host="0.0.0.0:8200"
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
        -E output.elasticsearch.username=${ELASTICSEARCH_USERNAME}
        -E output.elasticsearch.password=${ELASTICSEARCH_PASSWORD}
        -E apm-server.otlp.http.enabled=true

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}

volumes:
  postgres_data:
  elastic_data:
  minio_data:
